"""fix_foreign_key

Revision ID: 38aed3cdfd93
Revises: ad4e21e9c22c
Create Date: 2025-10-28 18:19:25.818170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38aed3cdfd93'
down_revision: Union[str, Sequence[str], None] = 'ad4e21e9c22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('refresh_tokens', 'is_locked')
    op.drop_constraint(op.f('uq_users_refresh_token_id'), 'users', type_='unique')
    op.drop_constraint(op.f('fk_users_refresh_token_id_refresh_tokens'), 'users', type_='foreignkey')
    op.drop_column('users', 'refresh_token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_refresh_token_id_refresh_tokens'), 'users', 'refresh_tokens', ['refresh_token_id'], ['id'])
    op.create_unique_constraint(op.f('uq_users_refresh_token_id'), 'users', ['refresh_token_id'], postgresql_nulls_not_distinct=False)
    op.add_column('refresh_tokens', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'is_active')
    # ### end Alembic commands ###
