"""add cascade delete

Revision ID: 754a84bf6a57
Revises: c560a476660d
Create Date: 2025-11-07 22:16:39.098256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754a84bf6a57'
down_revision: Union[str, Sequence[str], None] = 'c560a476660d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_refresh_tokens_user_id_users'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
