"""update_fields_and_relations

Revision ID: ad4e21e9c22c
Revises: d847a4f1e529
Create Date: 2025-10-28 16:48:27.372563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4e21e9c22c'
down_revision: Union[str, Sequence[str], None] = 'd847a4f1e529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('user_id', name=op.f('uq_refresh_tokens_user_id'))
    )
    op.drop_table('tokens')
    op.add_column('users', sa.Column('refresh_token_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_refresh_token_id'), 'users', ['refresh_token_id'])
    op.create_foreign_key(op.f('fk_users_refresh_token_id_refresh_tokens'), 'users', 'refresh_tokens', ['refresh_token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_refresh_token_id_refresh_tokens'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('uq_users_refresh_token_id'), 'users', type_='unique')
    op.drop_column('users', 'refresh_token_id')
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    sa.UniqueConstraint('user_id', name=op.f('uq_tokens_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
