"""fix_foreign_key

Revision ID: c560a476660d
Revises: 38aed3cdfd93
Create Date: 2025-10-28 19:12:36.724301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c560a476660d'
down_revision: Union[str, Sequence[str], None] = '38aed3cdfd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.drop_column('refresh_tokens', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'is_locked')
    # ### end Alembic commands ###
