"""change_field_name

Revision ID: d847a4f1e529
Revises: 34dd3321512e
Create Date: 2025-10-16 17:00:57.612581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd847a4f1e529'
down_revision: Union[str, Sequence[str], None] = '34dd3321512e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.String(length=256), nullable=False))
    # op.drop_constraint(op.f('uq_users_user_name'), 'users', type_='unique')
    # op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # op.drop_column('users', 'user_name')
    
    # custom migration
    op.alter_column('users', 'user_name', new_column_name='username')
    op.drop_constraint(op.f('uq_users_user_name'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    # op.create_unique_constraint(op.f('uq_users_user_name'), 'users', ['user_name'], postgresql_nulls_not_distinct=False)
    # op.drop_column('users', 'username')
    
    # custom migration
    op.alter_column('users', 'username', new_column_name='user_name')
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_user_name'), 'users', ['user_name'])
    
    # ### end Alembic commands ###
